# 大專校院各系所僑生、港澳生數
https://data.gov.tw/dataset/26210

In [65]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [70]:
df = pd.read_csv('學3-3.僑生、港澳生數及其在學比率-以「系所」統計.csv')
df.head()

,學年度,設立別,學校類別,學校統計處代碼,學校名稱,系所代碼,系所名稱,學制班別(日間),僑生小計,僑生男,僑生女,港澳生小計,港澳生男,港澳生女,僑生及港澳生數之在學比率(%)
0,106,公立,一般大學,0001,國立政治大學,01111001,教育學系,學士班(日間),19,2,17,5,3,2,10.04
1,106,公立,一般大學,0001,國立政治大學,01111001,教育學系,碩士班(日間),3,2,1,0,0,0,6.52
2,106,公立,一般大學,0001,國立政治大學,01114005,教育行政與政策研究所,碩士班(日間),1,1,0,1,0,1,4.26
3,106,公立,一般大學,0001,國立政治大學,01131002,華語文教學博士學位學程,博士班,1,0,1,0,0,0,5.26
4,106,公立,一般大學,0001,國立政治大學,01131002,華語文教學碩士學位學程,碩士班(日間),2,0,2,1,0,1,5.26

In [71]:
temp = df[['學年度','學校名稱', '僑生小計', '港澳生小計']]
temp

       學年度    學校名稱  僑生小計  港澳生小計
0      106  國立政治大學    19      5
1      106  國立政治大學     3      0
2      106  國立政治大學     1      1
3      106  國立政治大學     1      0
4      106  國立政治大學     2      1
...    ...     ...   ...    ...
15760  110  臺北市立大學     1      2
15761  110  臺北市立大學     6      9
15762  110  臺北市立大學     0      3
15763  110  臺北市立大學     7      9
15764  110  臺北市立大學     1      1

[15765 rows x 4 columns]

In [72]:
Type = temp.groupby(['學年度', '學校名稱']).sum().reset_index()

In [73]:
Type

     學年度           學校名稱  僑生小計  港澳生小計
0    106           世新大學   184    230
1    106           中原大學   182    373
2    106         中國文化大學   204    513
3    106         中國科技大學    19     13
4    106         中國醫藥大學   182    109
..   ...            ...   ...    ...
702  110  馬偕學校財團法人馬偕醫學院     3     11
703  110         高苑科技大學   107      3
704  110         高雄醫學大學   133     97
705  110         黎明技術學院   136      8
706  110         龍華科技大學   374     61

[707 rows x 4 columns]

# 10440-01-02-2 臺中市特殊教育學校教育經費概況(預、決算數)
https://data.gov.tw/dataset/90167

In [74]:
df2017 = pd.read_csv('2017_01_10440-01-02-2_臺中市特殊教育學校教育經費概況(預、決算數).csv')
df2017.head()

,RptNo,RptName,StatCourseNo,StatCourseName,DataDate,PlaceNo,PlaceName,PeriodNo,PeriodName,Complex1,ComplexName,Complex2,Complex2Name,Complex3,Complex3Name,Complex4,Complex4Name,Complex5,Complex5Name,DeriveNo,DeriveExplain,FValue,SValue,RptDeptNo,RptDeptName,CreateTime,ModifyTime
0,10440-01-02-2,臺中市特殊教育學校教育經費概況(預、決算數),1044001a017,特殊教育學校教育經費概況(預、決算數)-預算數-經費來源(單位:千元),2017/1/1 上午 12:00:00,10000066000,臺中市,Y,年,230010000101,國立,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,387040000E,教育局,2018/3/5 上午 09:38:17,2018/3/8 下午 03:26:39
1,10440-01-02-2,臺中市特殊教育學校教育經費概況(預、決算數),1044001a017,特殊教育學校教育經費概況(預、決算數)-預算數-經費來源(單位:千元),2017/1/1 上午 12:00:00,10000066000,臺中市,Y,年,230010000102,市立,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,429746,NaN,387040000E,教育局,2018/3/5 上午 09:38:17,2018/3/8 下午 03:26:39
2,10440-01-02-2,臺中市特殊教育學校教育經費概況(預、決算數),1044001a017,特殊教育學校教育經費概況(預、決算數)-預算數-經費來源(單位:千元),2017/1/1 上午 12:00:00,10000066000,臺中市,Y,年,2300100002,私立,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,65314,NaN,387040000E,教育局,2018/3/5 上午 09:38:17,2018/3/8 下午 03:26:39
3,10440-01-02-2,臺中市特殊教育學校教育經費概況(預、決算數),1044001a018,特殊教育學校教育經費概況(預、決算數)-預算數-經費支出(單位:千元),2017/1/1 上午 12:00:00,10000066000,臺中市,Y,年,230010000101,國立,2300400001,經常支出,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,387040000E,教育局,2018/3/5 上午 09:38:17,2018/3/8 下午 03:26:39
4,10440-01-02-2,臺中市特殊教育學校教育經費概況(預、決算數),1044001a018,特殊教育學校教育經費概況(預、決算數)-預算數-經費支出(單位:千元),2017/1/1 上午 12:00:00,10000066000,臺中市,Y,年,230010000102,市立,2300400001,經常支出,0,NaN,0,NaN,0,NaN,0,NaN,409354,NaN,387040000E,教育局,2018/3/5 上午 09:38:17,2018/3/8 下午 03:26:39

In [80]:
new = df2017[['Complex2Name', 'FValue']].groupby(['ComplexName'])['FValue'].sum().reset_index()
new['year'] = 2017
new

KeyError: 'ComplexName'